---
driver:
  name: openstack
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  openstack_region: <%= ENV['OS_REGION_NAME'] %>
  key_name: <%= ENV['OS_KEY_NAME'] %>
  flavor_ref: m1.medium
  network_ref: SHARESANDBOX
  openstack_network_name: SHARESANDBOX
  use_ipv6: true

platforms:
  - name: ubuntu-12.04
    driver:
      image_ref: /Ubuntu 12.04/
  - name: ubuntu-14.04
    driver:
      image_ref: /Ubuntu 14.04/

provisioner:
  name: salt_solo
  formula: mongodb
  pillars-from-files:
    mongodb.sls: test/fixtures/mongodb-norepo.sls
  pillars:
    top.sls:
      base:
        '*':
           - mongodb

suites:
  - name: server
    provisioner:
      state_top:
        base:
          '*':
            - mongodb

verifier:
  name: shell
  command: testinfra -vvv --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
