---
driver:
  name: vagrant

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

provisioner:
  name: salt_solo
  formula: mongodb
  pillars-from-files:
    mongodb.sls: test/fixtures/mongodb-norepo.sls
  pillars:
    top.sls:
      base:
        '*':
           - mongodb

suites:
  - name: server
    provisioner:
      state_top:
        base:
          '*':
            - mongodb

verifier:
  name: shell
  command: testinfra -vvv --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
